services:
  OxidEsales\EshopCommunity\Internal\Module\Install\ModuleCopyServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\ModuleCopyService
    arguments:
      $fileSystemService: '@oxid_esales.symfony.file_system'
    autowire: true
  OxidEsales\EshopCommunity\Internal\Module\Install\OxidEshopPackageFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\OxidEshopOxidEshopPackageFactory
    autowire: true
  OxidEsales\EshopCommunity\Internal\Module\Install\ModuleConfigurationInstallerInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\ModuleConfigurationInstaller
    autowire: true