services:
  OxidEsales\EshopCommunity\Internal\Module\Install\Service\ModuleFilesInstallerInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\Service\ModuleFilesInstaller
    arguments:
      $fileSystemService: '@oxid_esales.symfony.file_system'
    autowire: true
  OxidEsales\EshopCommunity\Internal\Module\Install\Dao\OxidEshopPackageDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\Dao\OxidEshopPackageDao
    autowire: true
  OxidEsales\EshopCommunity\Internal\Module\Install\Service\ModuleConfigurationInstallerInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\Service\ModuleConfigurationInstaller
    autowire: true